---
- name: Configure Surgery Web Server
  hosts: surgeryWeb
  tasks:
  - name: Install xWebAdministration module
    win_psmodule:
      name: xWebAdministration
      state: present

  - name: Install IIS features that are required
    win_dsc:
      resource_name: WindowsFeature
      Name: '{{ item }}'
      Ensure: Present
    loop:
    - Web-Server
    - Web-ASP
    - Web-CGI
    - Web-ISAPI-Ext
    - Web-ISAPI-Filter
    - Web-Includes
    - Web-HTTP-Errors
    - Web-Common-HTTP
    - Web-Performance
    - WAS

  - name: Make surgery web directory
    win_file:
      state: directory
      path: c:\surgeryweb

  - name: load surgery repo
    win_copy:
      dest: c:\surgeryweb
      src: vbsrc/

  - name: Allow IIS to read repo
    win_acl:
      path: c:\surgeryweb
      user: IIS_IUSRS
      type: Allow
      state: present
      rights: ReadAndExecute,ListDirectory,Read
      propogation: InheritOnly

  - name: Create surgery website
    win_dsc:
      resource_name: xWebsite
      Name: Default Web Site
      State: Started
      PhysicalPath: C:\surgeryweb
      BindingInfo:
      - Protocol: http
        Port: 80
        IPAddress: '*'
      AuthenticationInfo:
        Anonymous: yes
        Basic: yes
        Digest: no
        Windows: yes
  - name: Share website directory
    ansible.windows.win_share:
      name: surgery
      description: surgery website
      path: c:\surgeryweb
      full: vagrant
- name: Configure Surgery DB Server
  hosts: surgeryDB
  tasks:
  - name: Install SqlServerDsc module
    win_psmodule:
      name: SqlServerDsc
      state: present
  - name: Configure SQL Server to listen over TCP
    win_dsc:
      resource_name: SqlProtocol
      Enabled: true
      InstanceName: MSSQLSERVER
      ProtocolName: TcpIp
