---
- name: Configure Surgery Web Server
  hosts: surgeryWeb
  tasks:
  - name: Install xWebAdministration module
    win_psmodule:
      name: xWebAdministration
      state: present

  - name: Install IIS features that are required
    win_dsc:
      resource_name: WindowsFeature
      Name: '{{ item }}'
      Ensure: Present
    loop:
    - Web-Server

  - name: Make surgery web directory
    file:
      state: directory
      path: c:\surgeryweb

  - name: Check out surgery repo
    git:
      dest: c:\surgeryweb
      repo: //vboxsrv/vagrant

  - name: Create new website
    win_dsc:
      resource_name: xWebsite
      Name: Default Web Site
      State: Started
      PhysicalPath: C:\vbsrc
      BindingInfo:
      # - Protocol: https
      #   Port: 8443
      #   CertificateStoreName: My
      #   CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
      #   HostName: DSCTest
      #   IPAddress: '*'
      #   SSLFlags: 1
      - Protocol: http
        Port: 80
        IPAddress: '*'
      AuthenticationInfo:
        Anonymous: no
        Basic: yes
        Digest: no
        Windows: yes